### ISSUE TITLE
Resources page updates

### ISSUE THREAD

**Issue by docquantum** [UNL-Game-Dev-Club/UNL-Game-Dev-Club.github.io#20]
The resources page should be updated to reflect changes and updates that have happened.

1. Game Engines
    - Unity 2018 -> Unity
    - Add Godot maybe?
2. Art Tools - 2D
    - Add aseprite and any other tools you all know of
3. Audio Tools
    - Add [LMMS](https://github.com/LMMS/lmms)
4. Other Online Resources
    - Maybe add github?

**Comment by friedev** [comment]
Should be resolved by 6cdfd97629f4bd17351ec9f5047ac16080ccc1f7, cf01f70eb023005e580a66c7c7b9bd0bed398441, and ee2af1bc2d2f9840c9a0c81feaec7ab2f91a508a.
