### ISSUE TITLE
Convert website to Jekyll

### ISSUE THREAD

**Issue by rclafferty** [UNL-Game-Dev-Club/UNL-Game-Dev-Club.github.io#5]

**Comment by docquantum** [comment]
## Basic Jekyll mantra:
- Have templates that dictate site look
- Use sass in place of css
- Use markdown documents in place of HTML to create articles that are automatically compiled into the template and presented as if it were HTML
- Markdown documents are sorted into folders with respect to site sections, more filtering can be done to allow for more automation control

## Why Jekyll?
- Will create less overhead in the future, no need to keep adding to a single large static page, every article will be full with it's own space that will still keep the summary format currently used
- Will allow for more control and easier changes to the template, allowing for same content but different look
- Markdown is simple and having every article be separate makes it modular, single HTML can get confusing to look at and is harder for newcomers to work on it.
- Github pages has Jekyll support

## Jekyll pages:

### Home
- Pulls in future events for News, will be in news folder but will filter based on date. See news for more info.

### Projects
- Articles of projects people are currently working on
- Every project file will have a Title, Summary, Full Article
    - Title and summary will be used for entries in Projects
    - Clicking on an entry takes the user to the full article which expands on the summary

### News
- Pulls in past events for News
- Every news file will have a Title, Date, Summary, Full Article
    - Title Date and Summary will be used for entries in News and Home
    - Clicking on an entry takes the user to the full article which expands on the summary

## Always static pages:

### Resources
- Debate: Leave as plain HTML or make it markdown and instead use individual files for every entry

### Contact
- Leave it as basic HTML, very easy to modify, doesn't need to be automated
